name: Deploy Cloudflare Worker

on:
    push:
        branches: [main]
        paths:
            - "worker/**"
    workflow_dispatch: # allow manual trigger

jobs:
    deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./worker

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Generate wrangler.toml from template
              env:
                BOT_STATE_KV_ID: ${{ secrets.BOT_STATE_KV_ID }}
                USER_PLANS_KV_ID: ${{ secrets.USER_PLANS_KV_ID }}
              run: |
                  sed -i "s/__BOT_STATE_KV_ID__/${BOT_STATE_KV_ID}/g" wrangler.toml
                  sed -i "s/__USER_PLANS_KV_ID__/${USER_PLANS_KV_ID}/g" wrangler.toml
                  echo "Generated wrangler.toml:"
                  cat wrangler.toml


            - name: Set Cloudflare Worker Secrets
              env:
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  BALE_BOT_TOKEN: ${{ secrets.BALE_BOT_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}               # Personal Access Token for triggering workflows
                  GITHUB_REPO: ${{ secrets.ACTION_GITHUB_REPO }}               # GITHUB REPO for triggering workflows
                  BALE_PAYMENT_TOKEN: ${{ secrets.BALE_PAYMENT_TOKEN }}
                  ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
                  WORKER_SECRET: ${{ secrets.WORKER_SECRET }}
              run: |
                  # Set each secret via wrangler
                  echo "$BALE_BOT_TOKEN" | npx wrangler secret put BALE_BOT_TOKEN
                  echo "$GITHUB_TOKEN" | npx wrangler secret put GITHUB_TOKEN
                  echo "$GITHUB_REPO" | npx wrangler secret put GITHUB_REPO
                  echo "$BALE_PAYMENT_TOKEN" | npx wrangler secret put BALE_PAYMENT_TOKEN
                  echo "$ADMIN_CHAT_ID" | npx wrangler secret put ADMIN_CHAT_ID
                  echo "$WORKER_SECRET" | npx wrangler secret put WORKER_SECRET


            - name: Deploy to Cloudflare
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  workingDirectory: "worker"
                  command: deploy
